name: dbt_dvh_macros
version: 1.0.0
config-version: 2
profile: integration_tests

quoting:
  database: false
  identifier: false
  schema: false

flags:
  send_anonymous_usage_stats: false

dispatch:
  - macro_namespace: dbt_dvh_macros
    search_order: [dbt_dvh_macros]

macro-paths:
  - "macros"
  - "../../macros"

#on-run-start:
#  - select 'hook start' from dual
#on-run-end:
#  - select 'hook end' from dual
