name: dbt_dvh_macros_integration_tests
version: 1.0.0
config-version: 2
profile: integration_tests

quoting:
  database: false
  identifier: false
  schema: false

flags:
  send_anonymous_usage_stats: false

macro-paths:
  - "macros"
  - "../../macros"

on-run-start:
  - select 'hook start' from dual

on-run-end:
  - select 'hook end' from dual
