integration-tests:
  target: testcontainer
  outputs:
    testcontainer:
      type: oracle
      user:
      pass:
      protocol:
      port:
      service:
      database:
      schema:
      session_info:
        action:
        client_identifier:
        client_info:
        module:
      retry_count: 1
      retry_delay: 5
      threads: 1